### ISSUE TITLE
The Wasabi implementation is adequate, but allows users to spend pre-mix and post-mix coins simultaneously

### ISSUE THREAD

**Issue by m1t0s1s** [nopara73/ScamouraiWallet#4]
https://old.reddit.com/r/Bitcoin/comments/ku97pu/which_coinjoin_service_is_recognized_by_the/

**Comment by nopara73** [comment]
Wrong repo, wrong timing, wrong argument.

**Comment by nopara73** [comment]
On a second thought, maybe I just don't understand what you mean. Feel free to elaborate and I consider reopening the issue.
